OptunaConfig:
  n_startup_trials: 1
  n_trials: 1
  n_jobs: 1
  study_direction: "maximize"

TrainingConfig:
  dynamic_dataset: True
  train_percentage: 1
  threshold_coverage: 100
  load_to_cpu: False
  epochs: 2

ValidationConfig:
  validation_mode:
    val_type: svms_model
    process_count: 1
    fail_immediately: false
    PlatformsConfig:
      - name: dotnet
        DatasetConfigs:
          - dataset_base_path: /home/mishka/Desktop/code/PySymGym/maps/DotNet/Maps/Root/bin/Release/net8.0
            dataset_description: ../workflow/dataset_stralgo_methods.json
        SVMSInfo:
          - name: VSharp
            launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode sendmodel --mapname {MapName} --model {ModelPath} --stepstoplay {StepsToPlay} --defaultsearcher {DefaultSearcher} --stepstostart {StepsToStart} --assemblyfullname {AssemblyFullName} --nameofobjecttocover {NameOfObjectToCover} --outfolder {OutputDir} --port {Port}
            server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net8.0
            min_port: 35100
            max_port: 35150

MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: Stralgo_Methods_Training
