OptunaConfig:
  n_startup_trials: 10
  n_trials: 20
  n_jobs: 1
  study_direction: 'maximize'
  trial_uri: mlflow-artifacts:/586711271782166545/cba13afe5ddd463485868fd215ba3d01/artifacts/trial.pkl

TrainingConfig:
  dynamic_dataset: True
  train_percentage: 1
  threshold_coverage: 100
  threshold_steps_number: 1000
  load_to_cpu: False 
  epochs: 30

ValidationConfig:
  validation_mode:
    val_type: svms_model
    process_count: 16
    PlatformsConfig:
      - name: dotnet
        DatasetConfigs:
          - dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
            dataset_description: ../maps/DotNet/Maps/dataset.json
        SVMSInfo:
          - name: VSharp
            launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode sendmodel --mapname {MapName} --model {ModelPath} --stepstoplay {StepsToPlay} --defaultsearcher {DefaultSearcher} --stepstostart {StepsToStart} --assemblyfullname {AssemblyFullName} --nameofobjecttocover {NameOfObjectToCover} --outfolder {OutputDir} --port {Port}
            min_port: 34000
            max_port: 34450
            server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net7.0

MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: SVM_PC_send_model_17.11.2025_BCE

weights_uri: mlflow-artifacts:/586711271782166545/cba13afe5ddd463485868fd215ba3d01/artifacts/20/model.pth