OptunaConfig:
  n_startup_trials: 10
  n_trials: 50
  n_jobs: 1
  study_direction: 'minimize'

TrainingConfig:
  dynamic_dataset: True
  train_percentage: 0.7
  threshold_coverage: 100
  threshold_steps_number: 1000
  load_to_cpu: False 
  epochs: 30

ValidationConfig:
  validation_mode:
    val_type: custom
    process_count: 8
    val_sequence:
      - val_type: loss
        batch_size: 50
      - val_type: loss
        batch_size: 50
        dataset: TRAINING
      - val_type: svms_each_step
        process_count: 8
        PlatformsConfig:
          - name: dotnet
            DatasetConfigs:
              - dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
                dataset_description: ../maps/DotNet/Maps/dataset.json
            SVMSInfo:
              - name: VSharp
                launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode server --port {port}
                min_port: 35000
                max_port: 35450
                server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net7.0

        # - name: java
        #   DatasetConfigs:
        #     - dataset_base_path: ../maps/Java/Maps/
        #       dataset_description: ../maps/Java/Maps/dataset.json
        #   SVMSInfo:
        #     - name: usvm
        #       launch_command: java -jar app.jar --mode server --port {port}
        #       min_port: 35500
        #       max_port: 35950
        #       server_working_dir: ../GameServers/usvm/usvm-ml-gameserver/build/libs/


MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: All_vals_01.05.2025
