OptunaConfig:
  n_startup_trials: 10
  n_trials: 50
  n_jobs: 1
  study_direction: 'minimize'

TrainingConfig:
  dynamic_dataset: False
  train_percentage: 0.7
  threshold_coverage: 100
  # threshold_steps_number: 1000
  load_to_cpu: True
  epochs: 300

ValidationConfig:
  validation_mode:
    val_type: loss
    batch_size: 50

MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: Optuna_05.11.2025_Murino_BCE
