OptunaConfig:
  n_startup_trials: 10
  n_trials: 20
  n_jobs: 1
  study_direction: 'maximize'
  trial_uri: mlflow-artifacts:/586711271782166545/cba13afe5ddd463485868fd215ba3d01/artifacts/trial.pkl

TrainingConfig:
  dynamic_dataset: True
  train_percentage: 1
  threshold_coverage: 100
  threshold_steps_number: 1000
  load_to_cpu: False 
  epochs: 30

ValidationConfig:
  validation_mode:
    val_type: svms_each_step
    process_count: 16
    PlatformsConfig:
      - name: dotnet
        DatasetConfigs:
          - dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
            dataset_description: ../maps/DotNet/Maps/dataset.json
        SVMSInfo:
          - name: VSharp
            launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode server --port {port}
            min_port: 35000
            max_port: 35450
            server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net7.0

      # - name: java
      #   DatasetConfigs:
      #     - dataset_base_path: ../maps/Java/Maps/
      #       dataset_description: ../maps/Java/Maps/dataset.json
      #   SVMSInfo:
      #     - name: usvm
      #       launch_command: java -jar app.jar --mode server --port {port}
      #       min_port: 35500
      #       max_port: 35950
      #       server_working_dir: ../GameServers/usvm/usvm-ml-gameserver/build/libs/


MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: SVMs_14.11.2025_BCE

weights_uri: mlflow-artifacts:/586711271782166545/cba13afe5ddd463485868fd215ba3d01/artifacts/20/model.pth
